name: Build and Deploy Batch

on:
  push:
    paths:
      - 'batch/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Prepare environment for badminton-batch
        run: |
          echo "${{ secrets.ENV }}" > ./batch/src/main/resources/.env
          echo "${{ secrets.LOGBACK_BATCH }}" > ./batch/src/main/resources/logback.xml

      - name: Set Gradle Wrapper Permissions
        run: chmod +x ./gradlew

      - name: Build badminton-batch
        run: ./gradlew :batch:assemble --parallel
        env:
          GRADLE_OPTS: -Dorg.gradle.daemon=false

      - name: Install Docker Compose plugin
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose-plugin

      - name: Build and push Docker image for badminton-batch
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker compose build badminton-batch
          docker compose push badminton-batch

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy badminton-batch
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PUBLIC_DNS }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "${{ secrets.DOCKERHUB_PASSWORD }}" | sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            echo "Deploying badminton-batch..."
            sudo docker compose pull badminton-batch
            sudo docker compose up -d badminton-batch
            sudo docker image prune -f
