name: Build and Deploy API

on:
  push:
    branches:
      - release
    paths:
      - 'batch/**'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set environment values for Batch
        run: |
          cd ./batch/src/main/resources
          touch ./.env
          echo "${{ secrets.ENV }}" > ./.env

      - name: Generate logback.xml for API
        run: |
          cd ./batch/src/main/resources
          cat <<EOF > logback.xml
          ${{ secrets.LOGBACK_API }}
          EOF

      - name: Set Gradle Wrapper Permissions
        run: chmod +x ./gradlew

      - name: Build API
        run: ./gradlew :batch:assemble

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and push Docker image for Batch
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker compose build badminton-batch
          docker compose push badminton-batch

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy Batch on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PUBLIC_DNS }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Docker Hub에 로그인"
            echo "${{ secrets.DOCKERHUB_PASSWORD }}" | sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            echo "badminton-batch 서비스 업데이트"
            sudo docker compose pull badminton-batch
            sudo docker compose up -d badminton-batch
            echo "오래된 Docker 이미지 정리"
            sudo docker image prune -f
